
use QLSVLab4Nhom

select * from SINHVIEN
select * from BANGDIEM

Delete from BANGDIEM where MASV = 'SV006' 

ALTER TABLE BANGDIEM 
DROP CONSTRAINT FK_SV;

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_SV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

